package database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.said.homework.news.data.model.ArticleDB;

import database.ArticleDBDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig articleDBDaoConfig;

    private final ArticleDBDao articleDBDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        articleDBDaoConfig = daoConfigMap.get(ArticleDBDao.class).clone();
        articleDBDaoConfig.initIdentityScope(type);

        articleDBDao = new ArticleDBDao(articleDBDaoConfig, this);

        registerDao(ArticleDB.class, articleDBDao);
    }
    
    public void clear() {
        articleDBDaoConfig.clearIdentityScope();
    }

    public ArticleDBDao getArticleDBDao() {
        return articleDBDao;
    }

}
