package database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.said.homework.news.data.model.ArticleDB;
import com.said.homework.news.data.model.ArticleSourceDB;

import database.ArticleDBDao;
import database.ArticleSourceDBDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig articleDBDaoConfig;
    private final DaoConfig articleSourceDBDaoConfig;

    private final ArticleDBDao articleDBDao;
    private final ArticleSourceDBDao articleSourceDBDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        articleDBDaoConfig = daoConfigMap.get(ArticleDBDao.class).clone();
        articleDBDaoConfig.initIdentityScope(type);

        articleSourceDBDaoConfig = daoConfigMap.get(ArticleSourceDBDao.class).clone();
        articleSourceDBDaoConfig.initIdentityScope(type);

        articleDBDao = new ArticleDBDao(articleDBDaoConfig, this);
        articleSourceDBDao = new ArticleSourceDBDao(articleSourceDBDaoConfig, this);

        registerDao(ArticleDB.class, articleDBDao);
        registerDao(ArticleSourceDB.class, articleSourceDBDao);
    }
    
    public void clear() {
        articleDBDaoConfig.clearIdentityScope();
        articleSourceDBDaoConfig.clearIdentityScope();
    }

    public ArticleDBDao getArticleDBDao() {
        return articleDBDao;
    }

    public ArticleSourceDBDao getArticleSourceDBDao() {
        return articleSourceDBDao;
    }

}
